import { Role } from "./state";

export const rolePermissions: Array<Role> = [
    {
        id: 1,
        name: 'admin',
        permissions: [
            { module: 'dashboard', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'monitoring', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'rekonsiliasi', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'master_data', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'profil_kcp', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'verifikasi_biaya_atribusi', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'verifikasi_biaya_rutin', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'verifikasi_produksi', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'biaya_npp_nasional', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_kertas_kerja_verifikasi', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_verifikasi_pendapatan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_prognosa_pendapatan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_verifikasi_biaya', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_prognosa_biaya', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_realisasi_dana_lpu', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_deviasi_dana_lpu', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_berita_acara_penarikan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_berita_acara_verifikasi', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_berita_acara_verifikasi_bulanan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_profil_bo_lpu', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_cakupan_wilayan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_monitoring_kantor_existing', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_monitoring_kantor_usulan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_verifikasi_lapangan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_perbaikan_ringan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'manajemen_api', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'sync_log', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'user_log', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_rekening_biaya', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_rekening_produksi', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_provinsi', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_kabupaten_kota', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_kecamatan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_kelurahan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_nama_penyelenggara', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_jenis_kantor', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_regional', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_kc_kcu', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_kategori_biaya', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_tipe_bisnis', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'manajemen_user', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'ganti_password', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'manajemen_kunci_verifikasi', canView: true, canCreate: true, canUpdate: true, canDelete: true },
        ]
    },
    {
        id: 2,
        name: "Operator",
        permissions: [
            { module: 'dashboard', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'monitoring', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'rekonsiliasi', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'master_data', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'profil_kcp', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'verifikasi_biaya_atribusi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'verifikasi_biaya_rutin', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'verifikasi_produksi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'biaya_npp_nasional', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_kertas_kerja_verifikasi', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_verifikasi_pendapatan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_prognosa_pendapatan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_verifikasi_biaya', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_prognosa_biaya', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_realisasi_dana_lpu', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_deviasi_dana_lpu', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_berita_acara_penarikan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_berita_acara_verifikasi', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_berita_acara_verifikasi_bulanan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_profil_bo_lpu', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_cakupan_wilayan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_monitoring_kantor_existing', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_monitoring_kantor_usulan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_verifikasi_lapangan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_perbaikan_ringan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'manajemen_api', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'sync_log', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'user_log', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_rekening_biaya', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_rekening_produksi', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_provinsi', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_kabupaten_kota', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_kecamatan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_kelurahan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_nama_penyelenggara', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_jenis_kantor', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_regional', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_kc_kcu', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_kategori_biaya', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'referensi_tipe_bisnis', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'manajemen_user', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'ganti_password', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'manajemen_kunci_verifikasi', canView: true, canCreate: true, canUpdate: true, canDelete: true },
          ],
    },
    {
        id: 3,
        name: "Verifikator Website",
        permissions: [
            { module: 'dashboard', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'monitoring', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'rekonsiliasi', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'master_data', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'profil_kcp', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'verifikasi_biaya_atribusi', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'verifikasi_biaya_rutin', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'verifikasi_produksi', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'biaya_npp_nasional', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_kertas_kerja_verifikasi', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_verifikasi_pendapatan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_prognosa_pendapatan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_verifikasi_biaya', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_prognosa_biaya', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_realisasi_dana_lpu', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_deviasi_dana_lpu', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_berita_acara_penarikan', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_berita_acara_verifikasi', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_berita_acara_verifikasi_bulanan', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_profil_bo_lpu', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_cakupan_wilayan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_monitoring_kantor_existing', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_monitoring_kantor_usulan', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_verifikasi_lapangan', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_perbaikan_ringan', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'manajemen_api', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'sync_log', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'user_log', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_rekening_biaya', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_rekening_produksi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_provinsi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kabupaten_kota', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kecamatan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kelurahan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_nama_penyelenggara', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_jenis_kantor', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_regional', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kc_kcu', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kategori_biaya', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_tipe_bisnis', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'manajemen_user', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'ganti_password', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'manajemen_kunci_verifikasi', canView: false, canCreate: false, canUpdate: false, canDelete: false },
        ],
    },
    {
        id: 4,
        name: "Verifikator Mobile",
        permissions: [
            { module: 'dashboard', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'monitoring', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'rekonsiliasi', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'master_data', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'profil_kcp', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'verifikasi_biaya_atribusi', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'verifikasi_biaya_rutin', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'verifikasi_produksi', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'biaya_npp_nasional', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_kertas_kerja_verifikasi', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_verifikasi_pendapatan', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_prognosa_pendapatan', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_verifikasi_biaya', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_prognosa_biaya', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_realisasi_dana_lpu', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_deviasi_dana_lpu', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_berita_acara_penarikan', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_berita_acara_verifikasi', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_berita_acara_verifikasi_bulanan', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_profil_bo_lpu', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_cakupan_wilayan', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_monitoring_kantor_existing', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_monitoring_kantor_usulan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_verifikasi_lapangan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_perbaikan_ringan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'manajemen_api', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'sync_log', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'user_log', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_rekening_biaya', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_rekening_produksi', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_provinsi', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kabupaten_kota', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kecamatan', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kelurahan', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_nama_penyelenggara', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_jenis_kantor', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_regional', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kc_kcu', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kategori_biaya', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_tipe_bisnis', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'manajemen_user', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'ganti_password', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'manajemen_kunci_verifikasi', canView: false, canCreate: false, canUpdate: false, canDelete: false },
        ],
    },
    {
        id: 5,
        name: "Kominfo",
        permissions: [
            { module: 'dashboard', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'monitoring', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'rekonsiliasi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'master_data', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'profil_kcp', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'verifikasi_biaya_atribusi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'verifikasi_biaya_rutin', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'verifikasi_produksi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'biaya_npp_nasional', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_kertas_kerja_verifikasi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_verifikasi_pendapatan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_prognosa_pendapatan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_verifikasi_biaya', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_prognosa_biaya', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_realisasi_dana_lpu', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_deviasi_dana_lpu', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_berita_acara_penarikan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_berita_acara_verifikasi', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_berita_acara_verifikasi_bulanan', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'laporan_profil_bo_lpu', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_cakupan_wilayan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_monitoring_kantor_existing', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_monitoring_kantor_usulan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_verifikasi_lapangan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_perbaikan_ringan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'manajemen_api', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'sync_log', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'user_log', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_rekening_biaya', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_rekening_produksi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_provinsi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kabupaten_kota', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kecamatan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kelurahan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_nama_penyelenggara', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_jenis_kantor', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_regional', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kc_kcu', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kategori_biaya', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_tipe_bisnis', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'manajemen_user', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'ganti_password', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'manajemen_kunci_verifikasi', canView: false, canCreate: false, canUpdate: false, canDelete: false },
        ],
    },
    {
        id: 6,
        name: "Non Kominfo",
        permissions: [
            { module: 'dashboard', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'monitoring', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'rekonsiliasi', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'master_data', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'profil_kcp', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'verifikasi_biaya_atribusi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'verifikasi_biaya_rutin', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'verifikasi_produksi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'biaya_npp_nasional', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_kertas_kerja_verifikasi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_verifikasi_pendapatan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_prognosa_pendapatan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_verifikasi_biaya', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_prognosa_biaya', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_realisasi_dana_lpu', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_deviasi_dana_lpu', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_berita_acara_penarikan', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_berita_acara_verifikasi', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_berita_acara_verifikasi_bulanan', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_profil_bo_lpu', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_cakupan_wilayan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_monitoring_kantor_existing', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_monitoring_kantor_usulan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_verifikasi_lapangan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_perbaikan_ringan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'manajemen_api', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'sync_log', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'user_log', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_rekening_biaya', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_rekening_produksi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_provinsi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kabupaten_kota', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kecamatan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kelurahan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_nama_penyelenggara', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_jenis_kantor', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_regional', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kc_kcu', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kategori_biaya', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_tipe_bisnis', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'manajemen_user', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'ganti_password', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'manajemen_kunci_verifikasi', canView: false, canCreate: false, canUpdate: false, canDelete: false },
        ],
    },
    {
        id: 7,
        name: "Non Kementerian Kominfo",
        permissions: [
            { module: 'dashboard', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'monitoring', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'rekonsiliasi', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'master_data', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'profil_kcp', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'verifikasi_biaya_atribusi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'verifikasi_biaya_rutin', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'verifikasi_produksi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'biaya_npp_nasional', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_kertas_kerja_verifikasi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_verifikasi_pendapatan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_prognosa_pendapatan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_verifikasi_biaya', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_prognosa_biaya', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_realisasi_dana_lpu', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_deviasi_dana_lpu', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_berita_acara_penarikan', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_berita_acara_verifikasi', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_berita_acara_verifikasi_bulanan', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_profil_bo_lpu', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_cakupan_wilayan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_monitoring_kantor_existing', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_monitoring_kantor_usulan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_verifikasi_lapangan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'laporan_perbaikan_ringan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'manajemen_api', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'sync_log', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'user_log', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_rekening_biaya', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_rekening_produksi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_provinsi', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kabupaten_kota', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kecamatan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kelurahan', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_nama_penyelenggara', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_jenis_kantor', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_regional', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kc_kcu', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_kategori_biaya', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'referensi_tipe_bisnis', canView: true, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'manajemen_user', canView: false, canCreate: false, canUpdate: false, canDelete: false },
            { module: 'ganti_password', canView: true, canCreate: true, canUpdate: true, canDelete: true },
            { module: 'manajemen_kunci_verifikasi', canView: false, canCreate: false, canUpdate: false, canDelete: false },
        ],
    },
]